name: Gatsby Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      run: |
        touch .env.production
        echo OPENAI_TOKEN=${{ secrets.GATSBY_OPENAI_TOKEN }} >> .env.production
        npm ci
        npm run build
        cp -avr ./roms ./public
        cp -avr ./Resume.pdf ./public
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GATSBY_PUBLISH }}
          deploy-branch: "gh-pages"
